<?php
echo "<h1>All Products</h1>";
echo "<br>";
echo "<hr>";
echo PHP_EOL;
?>
<form method="post">
<input type="text" id="mySearch" name="search" placeholder="Search product by name.." title="Type in a category">
<button class="btn btn-success" type="submit">Search</button>
</form>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Additional</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($products as $k => $product) {
            echo '<tr>
                <th scope="row">' . $k . '</th>
                <td>' . $product->name . '</td>
                <td>' . $product->category . '</td>
                <td>' . $product->price . '</td>
                <td>' . $product->stock . '</td>
                <td><button class="btn btn-info view_details " data-toggle="modal" data-target="#exampleModal" data="' . $product->_id . '" href="#" class="btn btn-info">View</button></td>
                <td>
                <a href="http://localhost:8080/product/editProduct/' . $product->_id . '">Edit</a>
                <a href="http://localhost:8080/product/deleteProduct/' . $product->_id . '">Delete</a></td>
            </tr>';
        }
        ?>

    </tbody>
</table>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Product's Additional information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <h4 class="text-primary">Meta Information</h6>
                <div class="modal-body meta-tag">

                </div>
                <hr>
                <div class="modal-body variation-tag">
                    <h4 class="text-primary">Variations</h6>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
        $(document).on("click", ".view_details", function(e) {
            e.preventDefault();
            var product_id = $(this).attr("data");
            $('div.meta-tag').html('');
            $('div.variation-tag').html('');
            $.ajax({
                    method: "POST",
                    url: "http://localhost:8080/product/getProductAdditionalData",
                    data: {
                        product_id: product_id,
                    },
                    datatype: 'JSON'
                })
                .done(function(product) {
                    product = $.parseJSON(product);
                    for (var k in product['meta_information']) {
                        if (product['meta_information'].hasOwnProperty(k)) {
                            $('div.meta-tag').append("<p>" + k + " : " + product['meta_information'][k]);
                        }
                    }
                    for (var target in product['variations']) {
                        $('div.variation-tag').append('<h6>Variation</h6>');
                        for (var v in product['variations'][target]) {
                            if (product['variations'][target].hasOwnProperty(v)) {
                                $('div.variation-tag').append("<p>" + v + " : " + product['variations'][target][v]);
                            }
                        }

                    }
                });
        })

    });
</script>