<div class="col-xs-12">

    <div class="col-md-12">
        <form id="form" action="http://localhost:8080/index/addNewProduct" method="post">
            <input name="variation" hidden value="" id="variation">
            <h3> Add New Product</h3>
            <div id="field">
                <div id="field0">
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="name">Product Name</label>
                        <div class="col-md-5">
                            <input id="name" name="name" type="text" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="category">Category Name</label>
                        <div class="col-md-5">
                            <input id="category" name="category" type="text" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="price">Price</label>
                        <div class="col-md-5">
                            <input id="price" name="price" type="number" min="0" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="stock">Stock</label>
                        <div class="col-md-5">
                            <input id="stock" name="stock" type="number" min="0" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>

                </div>
            </div>

            <!-- Button -->
            <div class="form-group">
                <div class="col-md-4">
                <div class="input_fields_wrap">
                    <button class="add_field_button btn bg-info">Add Variaction</button>
                </div>
                </div>
            </div>

            <br><br>
            <input type="submit" class="btn btn-success" value="Add product">
        </form>
    </div>

</div>


<script>
    
    $(document).ready(function() {
        var wrapper = $(".input_fields_wrap"); 
        var meta_field = $(".input_meta_wrap"); 
        var add_button = $(".add_field_button"); 
        var variation = 0;
        $(add_button).click(function(e) {
            e.preventDefault();
            $(wrapper).append('<div data="'+variation+'" class="border border-primary">\
                    <a href="#" class="remove_variation text-danger">Remove Variation</a>\
                    <a href="#" class="add_field text-info">Add More Fields</a>\
                    <div>\
                        <input type="text" placeholder="Field name" name="fields'+variation+'[]"/>\
                        <input placeholder="Value" type="text" name="values'+variation+'[]"/>\
                        <a href="#" class="remove_field text-danger">Remove</a>\
                    <div>\</div>');
                variation+=1;
            $("#variation").val(variation);
        });

        $(wrapper).on("click", ".remove_field", function(e) {
            e.preventDefault();
            $(this).parent('div').remove();
        })
        $(wrapper).on("click", ".remove_variation", function(e) {
            e.preventDefault();
            $(this).parent('div').remove();
        })
        $(wrapper).on("click", ".add_field", function(e) {
            e.preventDefault();
            let count = $(this).parent('div').attr("data");
            $(this).parent('div').append('<div>\
            <input type="text" placeholder="Field name" name="fields'+count+'[]"/>\
            <input placeholder="Value" type="text" name="values'+count+'[]"/>\
            <a href="#" class="remove_field text-danger">Remove</a>\
            </div>');
        })
    });
</script>