<div class="col-xs-12">

    <div class="col-md-12">
        <form id="form" action="http://localhost:8080/index/addNewProduct" method="post">
            <h3> Add New Product</h3>
            <div id="field">
                <div id="field0">
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="name">Product Name</label>
                        <div class="col-md-5">
                            <input id="name" name="name" type="text" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="category">Category Name</label>
                        <div class="col-md-5">
                            <input id="category" name="category" type="text" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="price">Price</label>
                        <div class="col-md-5">
                            <input id="price" name="price" type="number" min="0" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="stock">Stock</label>
                        <div class="col-md-5">
                            <input id="stock" name="stock" type="number" min="0" placeholder="" class="form-control input-md">

                        </div>
                    </div>
                    <br><br>

                </div>
            </div>

            <!-- Button -->
            <div class="form-group">
                <div class="col-md-4">
                    <h1>Add Meta Information</h1>
                    <div class="input_meta_wrap p-2">
                        <button class="add_meta_field_button btn border border-dark">
                            <img style=" height:20px ;width: 20px" src="https://media.istockphoto.com/vectors/black-plus-sign-positive-symbol-vector-id688550958?k=20&m=688550958&s=170667a&w=0&h=vwmBL25oWU3A26BASebi4wENUZ23pnYz9QKnBiw4EvE=">
                        </button>
                    </div>
                    <h1>Add Variation</h1>
                    <div class="input_fields_wrap p-2">
                        <button class="add_field_button btn border border-dark"><img style=" height:20px ;width: 20px" src="https://media.istockphoto.com/vectors/black-plus-sign-positive-symbol-vector-id688550958?k=20&m=688550958&s=170667a&w=0&h=vwmBL25oWU3A26BASebi4wENUZ23pnYz9QKnBiw4EvE="></button>
                    </div>
                </div>
            </div>

            <br><br>
            <input type="submit" class="btn btn-success" value="Add product">
        </form>
    </div>

</div>


<script>
    $(document).ready(function() {
        var wrapper = $(".input_fields_wrap");
        var meta_div = $(".input_meta_wrap");
        var add_button = $(".add_field_button");
        var add_meta_button = $(".add_meta_field_button");
        $(add_meta_button).click(function(e) {
            e.preventDefault();
            $(meta_div).append('<div class="border border-primary p-2 m-2">\
                        <button class="remove_field btn border border-dark">\
                            <img style="display:inline; height:20px ;width: 20px" src="https://media.istockphoto.com/vectors/black-minus-sign-negative-symbol-vector-id688548090?k=20&m=688548090&s=170667a&w=0&h=xVmB2eSVy3nX8zpGOxzo9loLO1FMglDGUx8vX0arlI0=">\
                        </button>\
                    <div class="m-2">\
                        <input type="text" placeholder="Field name" name="meta_fields[]"/>\
                        <input placeholder="Value" type="text" name="meta_values[]"/>\
                      <div></div>');
        });
        $(add_button).click(function(e) {
            e.preventDefault();
            $(wrapper).append('<div class="border border-primary p-2 m-2">\
                        <button class="remove_variation btn border border-dark">\
                            <img style="display:inline; height:20px ;width: 20px" src="https://media.istockphoto.com/vectors/black-minus-sign-negative-symbol-vector-id688548090?k=20&m=688548090&s=170667a&w=0&h=xVmB2eSVy3nX8zpGOxzo9loLO1FMglDGUx8vX0arlI0=">\
                        </button>\
                    <div>\
                        <input type="text" placeholder="Color" name="values[]"/>\
                        <input placeholder="Size" type="text" name="values[]"/>\
                        <input placeholder="Price" type="text" name="values[]"/>\
                    <div>\</div>');
        });

        $(document).on("click", ".remove_field", function(e) {
            e.preventDefault();
            $(this).parent('div').remove();
        })
        $(wrapper).on("click", ".remove_variation", function(e) {
            e.preventDefault();
            $(this).parent('div').remove();
        })
        $(wrapper).on("click", ".add_field", function(e) {
            e.preventDefault();
            let count = $(this).parent('div').attr("data");
            $(this).parent('div').append('<div>\
            <input type="text" placeholder="Field name" name="fields' + count + '[]"/>\
            <input placeholder="Value" type="text" name="values' + count + '[]"/>\
            <a href="#" class="remove_field text-danger">Remove</a>\
            </div>');
        })
    });
</script>