<?php

echo "<h1>Hello World</h1>";
echo "<br>";
echo "<hr>";
echo PHP_EOL;
?>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Additional</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($products as $k => $product) {
            echo '<tr>
                <th scope="row">' . $k . '</th>
                <td>' . $product->name . '</td>
                <td>' . $product->category . '</td>
                <td>' . $product->price . '</td>
                <td>' . $product->stock . '</td>
                <td><a href="#" class="btn btn-info">View</a></td>
                <td>
                <a href="http://localhost:8080/product/editProduct/' . $product->_id . '">Edit</a>
                <a href="http://localhost:8080/product/deleteProduct/' . $product->_id . '">Delete</a></td>
            </tr>';
        }
        ?>

    </tbody>
</table>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>