<?php
echo "<h1>All Orders</h1>";
echo "<br>";
echo "<hr>";
echo PHP_EOL;
// foreach($orders as $order){
//     echo $order->product_name;
// }

?>
<form method="post">
    <label for="status">Select status</label>
    <select name="status" id="status">
        <option value="all">All</option>
        <option value="paid">Paid</option>
        <option value="Shipped">Shipped</option>
        <option value="Processing">Processing</option>
        <option value="Dispatched">Dispatched</option>
        <option value="Refunded">Refunded</option>
    </select>
    <label for="date">Select Order date</label>
    <select name="date" id="date">
        <option value="all">All</option>
        <option value="today">Today</option>
        <option value="this week">This Week</option>
        <option value="this month">This Month</option>
        <option value="custom">Custom</option>
    </select>
    <input type="submit" class="btn btn-success">
</form>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Variation</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
            <th scope="col">Date</th>
            <th scope="col">Add Status</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($orders as $k => $order) {
            echo '<tr>
                <th scope="row">' . $k . '</th>
                <td>' . $order->product_name . '</td>
                <td>' . $order->variation . '</td>
                <td>' . $order->customer . '</td>
                <td>' . $order->quantity . '</td>
                <td class="status">' . $order->status . '</td>
                <td>' . $order->order_date . '</td>
                <td><input class="order-id" hidden value="' . $order->_id . '"><button class="edit visible">Edit</button><button class="update invisible">Update</button></td>
            </tr>';
        }
        ?>
    </tbody>
    <script>
        $(document).ready(function() {
            $('.edit').on('click', function() {
                $(this).hide();
                $(this).siblings("button").removeClass('invisible');
                $(this).parent().siblings(".status").html('<select name="status" id="status">\
                                <option value="paid">Paid</option>\
                                <option value="shipped">Shipped</option>\
                                <option value="processing">Processing</option>\
                                <option value="dispatched">Dispatched</option>\
                                <option value="refunded">Refunded</option>\
                                </select>')
            })
            $('.update').on('click', function() {
                $(this).hide();
                $(this).siblings("button").show();
                // console.log($(this).parent().siblings(".status").find('option:selected').text());
                $.ajax({
                        method: "POST",
                        url: "http://localhost:8080/order/editOrderStatus",
                        data: {
                            order_id: $(this).siblings("input").val(),
                            status: $(this).parent().siblings(".status").find('option:selected').text()
                        },
                        datatype: 'JSON'
                    })
                    .done(function() {
                        location.reload();
                    })
            })
            $('select#date').on('change', function() {
                if (this.value == 'custom') {
                    $(this).parent("form").append("<label for='start_date'>Start date</label><input name='start_date' type=date>\
                    <label for='end_date'>End date</label><input name='end_date' type=date>");
                }

            });
        });
    </script>